# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def common_pods
    pod 'FirebaseMessaging'
    pod 'FirebaseRemoteConfig'
    pod 'GooglePlaces'
    pod 'GoogleMaps'
    pod 'GoogleAnalytics'
    pod 'Mixpanel-swift'
    pod 'AppsFlyerFramework'
    pod 'PhoneNumberKit', '~> 2.5'
end

target 'UrbanPiperSDK' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    common_pods
end

target 'UrbanPiperSDK-Example' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    common_pods
    
end

