# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def common_pods
    pod 'FirebaseMessaging'
    pod 'Firebase/RemoteConfig'
    pod 'GooglePlaces'
    pod 'GoogleMaps'
    pod 'GoogleAnalytics'
    pod 'Mixpanel-swift'
    pod 'AppsFlyerFramework'
end

target 'UrbanPiperSDK' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    common_pods
    
end

target 'UrbanPiperSDK-Example' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    common_pods
    
end

